github_user_name: blackmajique

# Culori cool pentru snake și doturi
color_snake: "#00ffff"
color_dots: "#39FF14,#FF6AC1,#FAFF00,#FF3131,#F97FFF"

# Dark mode + output
theme: dark
output: github-contribution-grid-snake.svg
