name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake inline 💖
        uses: Platane/snk@v3
        with:
          github_user_name: blackmajique
          color_snake: "#FF69B4"
          color_dots: "#FFB6C1,#FF69B4,#FF85B3,#FFC0CB,#DB7093"
          theme: dark
          transparent: true
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
