name: Metrics Snake Pink

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_contributors: yes
          plugin_isocalendar: yes
          plugin_achievements: yes
          config_timezone: Europe/Bucharest
          config_padding: 10%
          config_twemoji: yes
