name: Generate Snake Pink

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub snake contribution grid
        uses: lowlighter/metrics@latest
        with:
          filename: github-contribution-grid-snake.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_skyline: no
          plugin_skyline_year: 2024
          plugin_skyline_frames: 60
          plugin_skyline_quality: 1
          plugin_skyline_color: pink
